### ISSUE TITLE
#1 RBL - Penyederhanaan Deteksi Gambar Menjadi Dataframe atau database saja

### ISSUE THREAD

**Issue by MarcoSutisna** [MarcoSutisna/Tugas-Visualisasi#2]
to do list:

1. Menentukan makanan mana saja yang akan dimasukan
2. Membuat dataframe atau database dalam code python
3. Pemilihan visualisasi - Cari contoh visualisasi lain yang sederhana lalu dibandingkan dengan visualisasi usulan.

**Comment by MarcoSutisna** [comment]
Progress Week 1: https://osf.io/tdgax

1. Menentukan makanan mana saja yang akan dimasukan **(on progress)**
2. Membuat dataframe dalam code python **(done)** 
3. Pemilihan visualisasi - Cari contoh visualisasi lain yang sederhana lalu dibandingkan dengan visualisasi usulan. **(not start)**


Another Update:
1. Menemukan metode yang akan digunakan untuk sistem rekomendasi

Marco Sutisna Putra
20924001

**Comment by dudung** [comment]
Apakah ada problem yang diperkirakan akan dihadapi, @MarcoSutisna? Problem dapat dideskripsikan sehingga rekan yang lain dapat membantu memberikan saran.

**Comment by MarcoSutisna** [comment]
Perihal proble, ada pa @dudung , 
Problem/kendala yang dihadapi:

1. Teknis: Coding untuk sistem rekomendasi - dalam menentukan jarak kalori harian yang dibutuhkan dengan kalori yang sudah di konsumsi saya berencana menggunakan greedy algorithm namun untuk fungsi constraintnya saya masih ragu apakah memang ide yang saya usulkan dengan menghitung kalori protein, lemak dan karbohidrat ini sudah tepat atau belum.

**Comment by dudung** [comment]
Ok. Silakan disampaikan penyelesaiannya. Dan bila sudah solved, issue ini bisa ditutup, @MarcoSutisna.

Setiap problem satu issue.

**Comment by MarcoSutisna** [comment]
Baik pa @dudung ,  Proses penyelesaiannya sudah dilakukan


untuk progress dan update terbaru serta penyelesaian sebelumnya, bisa di cek di issue terbaru https://github.com/MarcoSutisna/Tugas-Visualisasi/issues/3 dan slide https://osf.io/6347k terbaru
