### ISSUE TITLE
#2 RBL - Progress Visualisasi dan Dataframe

### ISSUE THREAD

**Issue by MarcoSutisna** [MarcoSutisna/Tugas-Visualisasi#3]
**yang sudah dilakukan:**
1. Update Dataframe List Makanan
2. Perlu ada visualisasi terkait batas makanan / kalori yang bisa ditampilkan dalam bentuk descriptive dan diagram
3. Perbandingan protein, kalori atau karbo yang dibutuhkan oleh tubuh
4. Rekomendasi pengurutan makanan berdasarkan apa? 

**yang akan dilakukan:**
1. Visualisasi trend dalam bentuk harian ataupun mingguan (rencananya menggunakan diagram garis untuk kalori dan diagram batang berlevel untuk nutrisi)
2. Visualisasi diagram lingkaran/batang untuk melihat seberapa sering makanan dipilih.
3. Rekomendasi makanan sudah dapat divisualisasikan

**Comment by MarcoSutisna** [comment]
Link Slide detail : https://osf.io/6347k

**Comment by dudung** [comment]
Mungkin setiap problem dalam satu issue terpisah agar saat selesai dapat ditutup. Bila dicampur, misalnya tiga problem, issue terkait baru dapat ditutup setelah ketiganya selesai.

**Comment by MarcoSutisna** [comment]
Baik pa @dudung  sudah diuraikan untuk problem pada progress minggu ini.
untuk issues ini sudah solved dan dokumentasinya ada pada: https://osf.io/mq6he

Terima kasih pa
